### ISSUE TITLE
Misnamed and Missing Files

### ISSUE THREAD

**Issue by willchoprojects** [rolley1990/HybridModel_PLOS_CompBio#1]
Hello!

Thank you so much for sharing this code!
I was wondering if there are files under `Case_Study1>Experiment_Observation` that are missing.
It seems like `case_det_wrong.m` isn't in the folder, and `case_det.m` is wrongly named as `case_det,m` – please let me know otherwise!

**Comment by rolley1990** [comment]
Thank you for the comments. I have corrected the errors you pointed out.

Best
